---
# tasks file for kops
- name: "{{ role_action }} - {{ role_name }} {{ cluster_id }}"
  debug:
    msg: "This is {{ role_action }} for {{ role_name }} {{ cluster_id }}"

- name: "Get all pods"
  local_action:
    module: shell
    cmd: "kubectl --kubeconfig={{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'CLUSTERS_DIR') }}/{{ cluster_id }}/kubeconfig get pods --all-namespaces"
  register: k3gpresult
  until: k3gpresult.rc == 0
  retries: 10
  delay: 10

- name: List all pods
  debug:
    msg: "{{ k3gpresult.stdout_lines }}"
