---
# tasks file for kube-audit
- name: "{{ role_action }} - {{ role_name }}"
  debug:
    msg: "This is {{ role_action }} for {{ role_name }}"

- name: "Create {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}"
  file:
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}"
    state: directory
    mode: 0755

- name: "Get available {{ role_name }} releases"
  local_action:
    module: copy
    src: "files/releases.json"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/releases.json"
