---
# tasks file for kops
- name: "{{ role_action }} - {{ role_name }} {{ release_version }}"
  debug:
    msg: "This is {{ role_action }} for {{ role_name }} version {{ release_version }}"

- name: "Create {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}"
  file:
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}"
    state: directory
    mode: 0755

- name: "Download {{ role_name }} release: {{ release_version }} linux"
  get_url:
    url: "{{ download_url }}"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ release_version }}.download"

- name: "Process downloaded file"
  copy:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ release_version }}.download"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ role_name }}-linux-amd64.tar.gz"
    mode: 0755

- name: "Untar downloaded file"
  unarchive:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ role_name }}-linux-amd64.tar.gz"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/"

- name: "kube-aws file x permissions"
  file:
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/linux-amd64/kube-aws"
    mode: 0755

- name: "Download {{ role_name }} release: {{ release_version }} darwin"
  get_url:
    url: "{{ download_url2 }}"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ release_version }}.download2"

- name: "Process downloaded file 2"
  copy:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ release_version }}.download2"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ role_name }}-darwin-amd64.tar.gz"
    mode: 0755

- name: "Untar downloaded file 2"
  unarchive:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/{{ role_name }}-darwin-amd64.tar.gz"
    dest: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/"

- name: "kube-aws file 2 x permissions"
  file:
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/{{ release_version }}/darwin-amd64/kube-aws"
    mode: 0755
