---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'CLUSTERS_DIR') }}/{{ cluster_id }}/profile.yml"
  roles:
    - { role: "kube-audit", role_action: "audit", cluster_id: "{{ cluster_id }}" }
