---
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: "{{ role_name }}", role_action: "{{ role_action }}", release_version: "{{ release_version }}", platform: "{{ platform }}" }
