---
# tasks file for gke
- name: "{{ role_action }} - {{ kubeatf.installer }} {{ cluster_id }}"
  debug:
    msg: "This is {{ role_action }} for {{ kubeatf.installer }} {{ cluster_id }}"

- name: "Destroy the cluster"
  local_action:
    module: shell
    cmd: "gcloud container clusters delete {{ kubeatf.profile_name }} --quiet"
  failed_when: (destroyresult.rc !=0) and (destroyresult.stderr.find("not found") == -1)
  register: destroyresult
  until: (destroyresult.rc == 0) or (destroyresult.stderr.find("not found") != -1)
  retries: 10
  delay: 20

- name: Show destroyed
  debug:
    msg: "{{ destroyresult.stdout_lines }}"

- name: Remove cluster folder
  local_action:
    module: file
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'CLUSTERS_DIR') }}/{{ cluster_id }}"
    state: absent
