---
# tasks file for gke
- name: "{{ role_action }} - {{ role_name }}"
  debug:
    msg: "This is {{ role_action }} for {{ role_name }}"

- name: "Create {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}"
  file:
    path: "{{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}"
    state: directory
    mode: 0755

- name: "Get available {{ role_name }} releases"
  local_action:
    module: shell
    cmd: "echo '[' > {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/releases.json && gcloud container get-server-config | grep \"^- [1|2]\" | sort -ru | sed -e 's/- /{\"tag_name\": \"/g' | sed -e 's/$/\", \"created_at\": \"unknown\"},/g' >> {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/releases.json && echo '{\"tag_name\": \"default\", \"created_at\": \"unknown\"}' >> {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/releases.json && echo ']' >> {{ lookup('env', 'PROJECT_PATH') }}/{{ lookup('env', 'RELEASES_DIR') }}/{{ role_name }}/releases.json"
